# Generated by Django 5.2.10 on 2026-01-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='checked_in', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(limit_choices_to={'role': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospital.patient')),
            ],
            options={
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=100)),
                ('report_file', models.FileField(upload_to='test_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='hospital.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
