# Generated by Django 5.2.10 on 2026-02-08 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patientvisit_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in URLs: /clinic/{slug}/', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('max_doctors', models.IntegerField(default=10)),
                ('max_patients', models.IntegerField(default=1000)),
                ('max_receptionists', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='checked_in_by',
            field=models.ForeignKey(limit_choices_to={'role': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_test_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Clinic Admin'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('lab_tech', 'Lab Technician')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='doctornotes',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='test',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='hospital.clinic'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hospital.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('clinic', 'license_number')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('clinic', 'patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('clinic', 'username')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'registration_date'], name='hospital_pa_clinic__4d49e6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'phone_number'], name='hospital_pa_clinic__aa399a_idx'),
        ),
    ]
