# Generated by Django 5.2.10 on 2026-02-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_clinic_alter_user_options_alter_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage_options', models.TextField(help_text="Comma-separated list: e.g., '500mg, 1000mg, 2000mg'")),
                ('frequency_options', models.TextField(help_text="Comma-separated list: e.g., 'Once daily, Twice daily, Thrice daily'")),
                ('default_frequency', models.CharField(blank=True, help_text='Default frequency suggestion', max_length=100)),
                ('default_duration', models.CharField(blank=True, help_text="Default duration suggestion: e.g., '7 days'", max_length=100)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Antibiotic, Pain Reliever, etc.'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_medicines', to='hospital.clinic')),
            ],
            options={
                'ordering': ['medicine_name'],
                'unique_together': {('clinic', 'medicine_name')},
            },
        ),
        migrations.CreateModel(
            name='MasterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('xray', 'X-Ray'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Cardiology, Pathology, etc.'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_tests', to='hospital.clinic')),
            ],
            options={
                'ordering': ['test_type', 'test_name'],
                'unique_together': {('clinic', 'test_name')},
            },
        ),
    ]
