# Generated by Django 5.2.10 on 2026-02-14 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_mastermedicine_mastertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('admission_type', models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('day_care', 'Day Care'), ('isolation', 'Isolation Ward')], default='general', max_length=50)),
                ('bed_number', models.CharField(blank=True, help_text="e.g., 'ICU-5', 'Ward-A-12'", max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('reason_for_admission', models.TextField(help_text='Chief complaint, symptoms')),
                ('medical_history', models.TextField(blank=True, help_text='Relevant past medical history')),
                ('allergies', models.TextField(blank=True, help_text='Drug allergies, food allergies, etc.')),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('in_treatment', 'In Treatment'), ('improving', 'Improving'), ('stable', 'Stable'), ('ready_for_discharge', 'Ready for Discharge'), ('discharged', 'Discharged'), ('shifted', 'Shifted to Another Facility'), ('deceased', 'Deceased')], default='admitted', max_length=30)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_admissions', to='hospital.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='hospital.patient')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('medication', 'Medication'), ('injection', 'Injection'), ('saline', 'Saline/IV Fluid'), ('oxygen', 'Oxygen Therapy'), ('procedure', 'Procedure/Surgery'), ('monitoring', 'Monitoring'), ('therapy', 'Physical Therapy'), ('other', 'Other')], max_length=50)),
                ('treatment_name', models.CharField(help_text='Name of medication, injection, procedure, etc.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, help_text="e.g., 'IV', 'IM', 'Oral', 'Inhalation'", max_length=100)),
                ('saline_type', models.CharField(blank=True, help_text="e.g., 'Normal Saline (0.9%)', 'D5W', 'Ringer's Lactate'", max_length=100)),
                ('quantity', models.CharField(blank=True, help_text="e.g., '500ml', '1L'", max_length=100)),
                ('oxygen_flow_rate', models.CharField(blank=True, help_text="e.g., '2L/min', '60%'", max_length=100)),
                ('oxygen_type', models.CharField(blank=True, help_text="e.g., 'Nasal Cannula', 'Mask', 'Ventilator'", max_length=100)),
                ('administered_date', models.DateTimeField()),
                ('duration', models.CharField(blank=True, help_text="e.g., '30 mins', '2 hours'", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Observations, patient response, any complications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_treatments', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_logs', to='hospital.patientadmission')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_logs', to='hospital.clinic')),
            ],
            options={
                'ordering': ['-administered_date'],
                'indexes': [models.Index(fields=['admission', '-administered_date'], name='hospital_tr_admissi_e6b44b_idx'), models.Index(fields=['clinic', '-administered_date'], name='hospital_tr_clinic__320aa0_idx')],
            },
        ),
    ]
