# Generated by Django 5.2.10 on 2026-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patientadmission_treatmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='admission_reason',
            field=models.TextField(blank=True, help_text='Reason for recommending admission'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='admission_recommended',
            field=models.BooleanField(default=False, help_text='Doctor recommends patient admission to hospital'),
        ),
    ]
