# Generated by Django 5.2.10 on 2026-02-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_prescription_admission_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patientvisit'),
        ),
    ]
