# Generated by Django 5.2.10 on 2026-02-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_prescription_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
    ]
