# Generated by Django 5.2.10 on 2026-02-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_prescription_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse', models.CharField(blank=True, max_length=20, null=True)),
                ('temp', models.CharField(blank=True, max_length=20, null=True)),
                ('spo2', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.clinic')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospital.prescription')),
            ],
        ),
    ]
