# Generated by Django 5.2.10 on 2026-02-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_user_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermedicine',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='mastermedicine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='common_dosages',
            field=models.CharField(blank=True, help_text='Example: 250mg, 500mg OR 5ml, 10ml', max_length=200),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='default_dosage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='default_schedule',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('morning_evening', 'Morning & Evening'), ('morning_night', 'Morning & Night'), ('afternoon_night', 'Afternoon & Night'), ('morning_afternoon_night', 'Morning, Afternoon & Night'), ('sos', 'SOS (If Needed)')], max_length=50),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='food_instruction',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('anytime', 'Anytime')], max_length=20),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermedicine',
            name='category',
            field=models.CharField(blank=True, help_text='Example: Antibiotic, Painkiller', max_length=100),
        ),
        migrations.AlterField(
            model_name='mastermedicine',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.clinic'),
        ),
        migrations.AlterField(
            model_name='mastermedicine',
            name='default_duration',
            field=models.CharField(blank=True, help_text='Example: 5 days, 1 week', max_length=50),
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='default_frequency',
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='dosage_options',
        ),
        migrations.RemoveField(
            model_name='mastermedicine',
            name='frequency_options',
        ),
    ]
