# Generated by Django 5.2.10 on 2026-02-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_alter_mastermedicine_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermedicine',
            name='category',
        ),
    ]
