# Generated by Django 5.2.10 on 2026-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_mastermedicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastermedicine',
            name='default_schedule',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('morning_evening', 'Morning & Evening'), ('morning_night', 'Morning & Night'), ('afternoon_night', 'Afternoon & Night'), ('morning_afternoon_night', 'Morning, Afternoon & Night'), ('sos', 'SOS (If Needed)')], default='morning', max_length=50),
        ),
    ]
