# Generated by Django 5.2.10 on 2026-03-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_patient_date_of_birth_patient_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermedicine',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_medicines', to='hospital.clinic'),
        ),
    ]
