# Generated by Django 5.2.10 on 2026-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='food_instruction',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('anytime', 'Anytime')], max_length=20),
        ),
    ]
