# Generated by Django 5.2.10 on 2026-03-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_medicine_food_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='schedule',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('morning_evening', 'Morning & Evening'), ('morning_night', 'Morning & Night'), ('afternoon_night', 'Afternoon & Night'), ('morning_afternoon_night', 'Morning, Afternoon & Night'), ('sos', 'SOS (If Needed)')], max_length=50),
        ),
    ]
