# Generated by Django 5.2.10 on 2026-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_medicine_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops')], default='tablet', max_length=20),
        ),
    ]
