# Generated by Django 5.2.10 on 2026-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_associatedmedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
