# Generated by Django 5.2.10 on 2026-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_medicine_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermedicine',
            name='frequency_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Example: 1=Once daily, 2=Twice daily, 3=Thrice daily'),
        ),
    ]
