# Generated by Django 5.2.10 on 2026-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_mastermedicine_frequency_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='frequency',
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Example: 1=Once daily, 2=Twice daily, 3=Thrice daily'),
        ),
    ]
