# Generated by Django 5.2.10 on 2026-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_remove_medicine_frequency_medicine_frequency_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotes',
            name='checkin_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'patient_name'], name='hospital_pa_clinic__b7d234_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'patient_id'], name='hospital_pa_clinic__8abc8c_idx'),
        ),
    ]
