# Generated by Django 5.2.10 on 2026-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0051_standardprescriptiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtemplatemedicine',
            name='food_instruction',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('anytime', 'Anytime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='standardtemplatemedicine',
            name='schedule',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('morning_evening', 'Morning & Evening'), ('morning_night', 'Morning & Night'), ('afternoon_night', 'Afternoon & Night'), ('morning_afternoon_night', 'Morning, Afternoon & Night'), ('sos', 'SOS (If Needed)')], max_length=50),
        ),
    ]
