# Generated by Django 5.2.10 on 2026-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0052_alter_standardtemplatemedicine_food_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='sugar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mastermedicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='standardtemplatemedicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion')], default='tablet', max_length=20),
        ),
    ]
