# Generated by Django 5.2.10 on 2026-04-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_vitals_sugar_alter_mastermedicine_medicine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermedicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion'), ('powder', 'Powder')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion'), ('powder', 'Powder')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='standardtemplatemedicine',
            name='medicine_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('soap', 'Soap'), ('lotion', 'Lotion'), ('powder', 'Powder')], default='tablet', max_length=20),
        ),
    ]
